"""add intent column to templates

Revision ID: b34f1bb6c8f1
Revises: t1b9c0d1e2f3
Create Date: 2026-05-26 12:26:44.124266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b34f1bb6c8f1'
down_revision: Union[str, Sequence[str], None] = 't1b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_audit_events_entity'), table_name='agent_audit_events')
    op.drop_index(op.f('ix_agent_audit_events_org_created'), table_name='agent_audit_events')
    op.drop_index(op.f('ix_agent_eval_runs_org_profile_created'), table_name='agent_eval_runs')
    op.drop_index(op.f('ix_agent_eval_runs_version'), table_name='agent_eval_runs')
    op.drop_index(op.f('ix_agent_performance_daily_org_bucket'), table_name='agent_performance_daily')
    op.drop_index(op.f('ix_agent_performance_daily_profile_bucket'), table_name='agent_performance_daily')
    op.drop_index(op.f('uq_agent_performance_daily_natural'), table_name='agent_performance_daily')
    op.drop_index(op.f('ix_agent_profiles_org_type_status'), table_name='agent_profiles')
    op.drop_index(op.f('uq_agent_profiles_org_slug_active'), table_name='agent_profiles', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_agent_prompt_configs_resolution'), table_name='agent_prompt_configs', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('uq_agent_prompt_configs_org_profile_scope_active'), table_name='agent_prompt_configs', postgresql_where="((status)::text = 'active'::text)")
    op.drop_constraint(op.f('agent_prompt_configs_active_version_id_fkey'), 'agent_prompt_configs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runtime_logs_org_hash_created'), table_name='agent_runtime_logs')
    op.drop_index(op.f('ix_agent_runtime_logs_org_profile_created'), table_name='agent_runtime_logs')
    op.drop_index(op.f('ix_agent_runtime_logs_run'), table_name='agent_runtime_logs')
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_doc_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_doc_chunks_org_category'), table_name='document_chunks')
    op.drop_index(op.f('ix_doc_chunks_org_team'), table_name='document_chunks')
    op.drop_index(op.f('ix_doc_chunks_org_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_doc_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_active'), table_name='document_chunks', postgresql_where="((archive_status)::text = 'active'::text)")
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_entities_active'), table_name='entities', postgresql_where="((archive_status)::text = 'active'::text)")
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_org_scope'), table_name='entities')
    op.drop_index(op.f('ix_entities_org_type'), table_name='entities')
    op.create_index(op.f('ix_entities_organization_id'), 'entities', ['organization_id'], unique=False)
    op.alter_column('entity_mentions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_entity_mentions_entity'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_org_category_doc'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_org_meeting'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_org_team_doc'), table_name='entity_mentions')
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    op.drop_index(op.f('ix_merge_suggestions_org_status'), table_name='entity_merge_suggestions')
    op.drop_index(op.f('uq_merge_suggestions_pair'), table_name='entity_merge_suggestions')
    op.alter_column('graph_extraction_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_runs_meeting'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_runs_org'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_runs_org_category_doc'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_runs_org_team_doc'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_runs_prompt_version'), table_name='graph_extraction_runs')
    op.create_index(op.f('ix_graph_extraction_runs_meeting_id'), 'graph_extraction_runs', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_graph_extraction_runs_organization_id'), 'graph_extraction_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_graph_extraction_runs_prompt_version'), 'graph_extraction_runs', ['prompt_version'], unique=False)
    op.alter_column('importance_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_importance_runs_org_created'), table_name='importance_runs')
    op.drop_index(op.f('ix_importance_runs_org_target'), table_name='importance_runs')
    op.alter_column('meeting_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meeting_chunks_active'), table_name='meeting_chunks', postgresql_where="((archive_status)::text = 'active'::text)")
    op.drop_index(op.f('ix_meeting_chunks_embedding_hnsw'), table_name='meeting_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_meeting_chunks_org_category'), table_name='meeting_chunks')
    op.drop_index(op.f('ix_meeting_chunks_org_team'), table_name='meeting_chunks')
    op.create_index(op.f('ix_meeting_chunks_id'), 'meeting_chunks', ['id'], unique=False)
    op.drop_index(op.f('ix_prompt_deployments_org_action_created'), table_name='prompt_deployments')
    op.drop_index(op.f('ix_prompt_deployments_org_config_created'), table_name='prompt_deployments')
    op.drop_index(op.f('ix_prompt_test_runs_org_created'), table_name='prompt_test_runs')
    op.drop_index(op.f('ix_prompt_test_runs_version_created'), table_name='prompt_test_runs')
    op.drop_index(op.f('ix_prompt_versions_config_state_version'), table_name='prompt_versions')
    op.drop_index(op.f('ix_chunk_access_chunk_event'), table_name='rag_chunk_access_events')
    op.drop_index(op.f('ix_chunk_access_org_chunk'), table_name='rag_chunk_access_events')
    op.drop_index(op.f('ix_chunk_access_org_created'), table_name='rag_chunk_access_events')
    op.drop_index(op.f('ix_chunk_access_run'), table_name='rag_chunk_access_events')
    op.drop_index(op.f('ix_citation_click_chunk'), table_name='rag_citation_click_events')
    op.drop_index(op.f('ix_citation_click_org_created'), table_name='rag_citation_click_events')
    op.drop_index(op.f('ix_citation_click_run'), table_name='rag_citation_click_events')
    op.alter_column('rag_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rag_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rag_conv_org_user_updated'), table_name='rag_conversations')
    op.alter_column('rag_query_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rag_runs_conv_created'), table_name='rag_query_runs')
    op.drop_index(op.f('ix_rag_runs_org_created'), table_name='rag_query_runs')
    op.drop_index(op.f('ix_rag_runs_org_user'), table_name='rag_query_runs')
    op.alter_column('relationship_mentions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rel_mentions_org_category_doc'), table_name='relationship_mentions')
    op.drop_index(op.f('ix_rel_mentions_org_team_doc'), table_name='relationship_mentions')
    op.drop_index(op.f('ix_relationship_mentions_org_meeting'), table_name='relationship_mentions')
    op.drop_index(op.f('ix_relationship_mentions_rel'), table_name='relationship_mentions')
    op.create_index(op.f('ix_relationship_mentions_relationship_id'), 'relationship_mentions', ['relationship_id'], unique=False)
    op.alter_column('relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('relationships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_relationships_active'), table_name='relationships', postgresql_where="((archive_status)::text = 'active'::text)")
    op.drop_index(op.f('ix_relationships_object'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_org_scope'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_subject'), table_name='relationships')
    op.create_index(op.f('ix_relationships_organization_id'), 'relationships', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_team_documents_status'), table_name='team_documents')
    op.add_column('template_behavior_profiles', sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.drop_index(op.f('ix_bp_lookup'), table_name='template_behavior_profiles')
    op.drop_index(op.f('ix_bp_parent_category_slug'), table_name='template_behavior_profiles', postgresql_where='(parent_category_slug IS NOT NULL)')
    op.drop_index(op.f('ux_bp_global_published'), table_name='template_behavior_profiles', postgresql_where="(((scope_kind)::text = 'global'::text) AND ((state)::text = 'published'::text))")
    op.drop_index(op.f('ux_bp_scope_slug_version'), table_name='template_behavior_profiles')
    op.drop_index(op.f('ix_template_bundle_items_bundle_ordering'), table_name='template_bundle_items')
    op.drop_index(op.f('ix_template_bundles_category_state'), table_name='template_bundles')
    op.drop_index(op.f('ix_template_bundles_published_recommended'), table_name='template_bundles', postgresql_where="((state)::text = 'published'::text)")
    op.drop_index(op.f('ix_template_provisioning_jobs_org_created'), table_name='template_provisioning_jobs')
    op.drop_index(op.f('ix_template_publish_events_kind_slug_created'), table_name='template_publish_events')
    op.drop_index(op.f('ix_behov_link_lookup'), table_name='workspace_behavior_overrides', postgresql_where='(workspace_template_link_id IS NOT NULL)')
    op.drop_index(op.f('ix_behov_scope_lookup'), table_name='workspace_behavior_overrides')
    op.drop_index(op.f('ux_behov_scope_int'), table_name='workspace_behavior_overrides', postgresql_where='(scope_id_int IS NOT NULL)')
    op.drop_index(op.f('ux_behov_scope_workspace'), table_name='workspace_behavior_overrides', postgresql_where="(((scope_type)::text = 'workspace'::text) AND (scope_id_uuid IS NULL) AND (scope_id_int IS NULL))")
    op.drop_index(op.f('ix_workspace_template_links_bundle'), table_name='workspace_template_links')
    op.drop_index(op.f('ix_workspace_template_links_org_kind_slug'), table_name='workspace_template_links')
    op.drop_index(op.f('ix_workspace_template_links_org_lineage_state'), table_name='workspace_template_links', postgresql_where="((lineage_state)::text <> 'pristine'::text)")
    op.drop_index(op.f('uq_workspace_template_links_entity'), table_name='workspace_template_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_workspace_template_links_entity'), 'workspace_template_links', ['entity_type', sa.literal_column("COALESCE(entity_id_uuid::text, ''::text)"), sa.literal_column("COALESCE(entity_id_int::text, ''::text)")], unique=True)
    op.create_index(op.f('ix_workspace_template_links_org_lineage_state'), 'workspace_template_links', ['organization_id', 'lineage_state'], unique=False, postgresql_where="((lineage_state)::text <> 'pristine'::text)")
    op.create_index(op.f('ix_workspace_template_links_org_kind_slug'), 'workspace_template_links', ['organization_id', 'source_template_kind', 'source_template_slug'], unique=False)
    op.create_index(op.f('ix_workspace_template_links_bundle'), 'workspace_template_links', ['source_bundle_id', 'source_template_version'], unique=False)
    op.create_index(op.f('ux_behov_scope_workspace'), 'workspace_behavior_overrides', ['organization_id', 'scope_type', 'dimension', 'field'], unique=True, postgresql_where="(((scope_type)::text = 'workspace'::text) AND (scope_id_uuid IS NULL) AND (scope_id_int IS NULL))")
    op.create_index(op.f('ux_behov_scope_int'), 'workspace_behavior_overrides', ['organization_id', 'scope_type', 'scope_id_int', 'dimension', 'field'], unique=True, postgresql_where='(scope_id_int IS NOT NULL)')
    op.create_index(op.f('ix_behov_scope_lookup'), 'workspace_behavior_overrides', ['organization_id', 'scope_type', 'scope_id_int', 'dimension'], unique=False)
    op.create_index(op.f('ix_behov_link_lookup'), 'workspace_behavior_overrides', ['workspace_template_link_id'], unique=False, postgresql_where='(workspace_template_link_id IS NOT NULL)')
    op.create_index(op.f('ix_template_publish_events_kind_slug_created'), 'template_publish_events', ['template_kind', 'template_slug', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_template_provisioning_jobs_org_created'), 'template_provisioning_jobs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_template_bundles_published_recommended'), 'template_bundles', ['is_recommended_on_signup'], unique=False, postgresql_where="((state)::text = 'published'::text)")
    op.create_index(op.f('ix_template_bundles_category_state'), 'template_bundles', ['category', 'state'], unique=False)
    op.create_index(op.f('ix_template_bundle_items_bundle_ordering'), 'template_bundle_items', ['bundle_id', 'ordering'], unique=False)
    op.create_index(op.f('ux_bp_scope_slug_version'), 'template_behavior_profiles', ['scope_kind', 'slug', 'version'], unique=True)
    op.create_index(op.f('ux_bp_global_published'), 'template_behavior_profiles', ['scope_kind', 'slug'], unique=True, postgresql_where="(((scope_kind)::text = 'global'::text) AND ((state)::text = 'published'::text))")
    op.create_index(op.f('ix_bp_parent_category_slug'), 'template_behavior_profiles', ['parent_category_slug'], unique=False, postgresql_where='(parent_category_slug IS NOT NULL)')
    op.create_index(op.f('ix_bp_lookup'), 'template_behavior_profiles', ['scope_kind', 'slug', 'state'], unique=False)
    op.drop_column('template_behavior_profiles', 'intent')
    op.create_index(op.f('ix_team_documents_status'), 'team_documents', ['status'], unique=False)
    op.drop_index(op.f('ix_relationships_organization_id'), table_name='relationships')
    op.create_index(op.f('ix_relationships_subject'), 'relationships', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_org_scope'), 'relationships', ['organization_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_relationships_object'), 'relationships', ['object_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_active'), 'relationships', ['organization_id'], unique=False, postgresql_where="((archive_status)::text = 'active'::text)")
    op.alter_column('relationships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_relationship_mentions_relationship_id'), table_name='relationship_mentions')
    op.create_index(op.f('ix_relationship_mentions_rel'), 'relationship_mentions', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_mentions_org_meeting'), 'relationship_mentions', ['organization_id', 'source_meeting_id'], unique=False)
    op.create_index(op.f('ix_rel_mentions_org_team_doc'), 'relationship_mentions', ['organization_id', 'source_team_document_id'], unique=False)
    op.create_index(op.f('ix_rel_mentions_org_category_doc'), 'relationship_mentions', ['organization_id', 'source_category_document_id'], unique=False)
    op.alter_column('relationship_mentions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_rag_runs_org_user'), 'rag_query_runs', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_rag_runs_org_created'), 'rag_query_runs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_rag_runs_conv_created'), 'rag_query_runs', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('rag_query_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_rag_conv_org_user_updated'), 'rag_conversations', ['organization_id', 'user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.alter_column('rag_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rag_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_citation_click_run'), 'rag_citation_click_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_citation_click_org_created'), 'rag_citation_click_events', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_citation_click_chunk'), 'rag_citation_click_events', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_access_run'), 'rag_chunk_access_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_chunk_access_org_created'), 'rag_chunk_access_events', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chunk_access_org_chunk'), 'rag_chunk_access_events', ['organization_id', 'chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_access_chunk_event'), 'rag_chunk_access_events', ['chunk_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_prompt_versions_config_state_version'), 'prompt_versions', ['agent_prompt_config_id', 'state', sa.literal_column('version_number DESC')], unique=False)
    op.create_index(op.f('ix_prompt_test_runs_version_created'), 'prompt_test_runs', ['prompt_version_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_prompt_test_runs_org_created'), 'prompt_test_runs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_prompt_deployments_org_config_created'), 'prompt_deployments', ['organization_id', 'agent_prompt_config_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_prompt_deployments_org_action_created'), 'prompt_deployments', ['organization_id', 'action', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_meeting_chunks_id'), table_name='meeting_chunks')
    op.create_index(op.f('ix_meeting_chunks_org_team'), 'meeting_chunks', ['organization_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_meeting_chunks_org_category'), 'meeting_chunks', ['organization_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_meeting_chunks_embedding_hnsw'), 'meeting_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_meeting_chunks_active'), 'meeting_chunks', ['organization_id'], unique=False, postgresql_where="((archive_status)::text = 'active'::text)")
    op.alter_column('meeting_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_importance_runs_org_target'), 'importance_runs', ['organization_id', 'target_kind'], unique=False)
    op.create_index(op.f('ix_importance_runs_org_created'), 'importance_runs', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('importance_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_graph_extraction_runs_prompt_version'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_extraction_runs_organization_id'), table_name='graph_extraction_runs')
    op.drop_index(op.f('ix_graph_extraction_runs_meeting_id'), table_name='graph_extraction_runs')
    op.create_index(op.f('ix_graph_runs_prompt_version'), 'graph_extraction_runs', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_graph_runs_org_team_doc'), 'graph_extraction_runs', ['organization_id', 'source_team_document_id'], unique=False)
    op.create_index(op.f('ix_graph_runs_org_category_doc'), 'graph_extraction_runs', ['organization_id', 'source_category_document_id'], unique=False)
    op.create_index(op.f('ix_graph_runs_org'), 'graph_extraction_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_graph_runs_meeting'), 'graph_extraction_runs', ['meeting_id'], unique=False)
    op.alter_column('graph_extraction_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uq_merge_suggestions_pair'), 'entity_merge_suggestions', ['organization_id', sa.literal_column('LEAST(candidate_a_id, candidate_b_id)'), sa.literal_column('GREATEST(candidate_a_id, candidate_b_id)')], unique=True)
    op.create_index(op.f('ix_merge_suggestions_org_status'), 'entity_merge_suggestions', ['organization_id', 'status'], unique=False)
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.create_index(op.f('ix_entity_mentions_org_team_doc'), 'entity_mentions', ['organization_id', 'source_team_document_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_org_meeting'), 'entity_mentions', ['organization_id', 'source_meeting_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_org_category_doc'), 'entity_mentions', ['organization_id', 'source_category_document_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity'), 'entity_mentions', ['entity_id'], unique=False)
    op.alter_column('entity_mentions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_entities_organization_id'), table_name='entities')
    op.create_index(op.f('ix_entities_org_type'), 'entities', ['organization_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entities_org_scope'), 'entities', ['organization_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_active'), 'entities', ['organization_id'], unique=False, postgresql_where="((archive_status)::text = 'active'::text)")
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_active'), 'document_chunks', ['organization_id'], unique=False, postgresql_where="((archive_status)::text = 'active'::text)")
    op.create_index(op.f('ix_doc_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_doc_chunks_org_type'), 'document_chunks', ['organization_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_doc_chunks_org_team'), 'document_chunks', ['organization_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_doc_chunks_org_category'), 'document_chunks', ['organization_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_doc_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_agent_runtime_logs_run'), 'agent_runtime_logs', ['rag_query_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runtime_logs_org_profile_created'), 'agent_runtime_logs', ['organization_id', 'agent_profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_agent_runtime_logs_org_hash_created'), 'agent_runtime_logs', ['organization_id', 'resolved_config_hash', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(op.f('agent_prompt_configs_active_version_id_fkey'), 'agent_prompt_configs', 'prompt_versions', ['active_version_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('uq_agent_prompt_configs_org_profile_scope_active'), 'agent_prompt_configs', ['organization_id', 'agent_profile_id', 'scope_type', sa.literal_column("COALESCE(scope_id, '-1'::integer::bigint)")], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_agent_prompt_configs_resolution'), 'agent_prompt_configs', ['organization_id', 'agent_profile_id', 'scope_type', 'scope_id'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('uq_agent_profiles_org_slug_active'), 'agent_profiles', ['organization_id', 'slug'], unique=True, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_agent_profiles_org_type_status'), 'agent_profiles', ['organization_id', 'agent_type', 'status'], unique=False)
    op.create_index(op.f('uq_agent_performance_daily_natural'), 'agent_performance_daily', ['organization_id', 'bucket_date', sa.literal_column("COALESCE(agent_profile_id::text, ''::text)"), sa.literal_column("COALESCE(prompt_version_id::text, ''::text)")], unique=True)
    op.create_index(op.f('ix_agent_performance_daily_profile_bucket'), 'agent_performance_daily', ['agent_profile_id', sa.literal_column('bucket_date DESC')], unique=False)
    op.create_index(op.f('ix_agent_performance_daily_org_bucket'), 'agent_performance_daily', ['organization_id', sa.literal_column('bucket_date DESC')], unique=False)
    op.create_index(op.f('ix_agent_eval_runs_version'), 'agent_eval_runs', ['prompt_version_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_agent_eval_runs_org_profile_created'), 'agent_eval_runs', ['organization_id', 'agent_profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_agent_audit_events_org_created'), 'agent_audit_events', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_agent_audit_events_entity'), 'agent_audit_events', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
