"""base_entity audit columns on all tables

Adds the four Base_Entity audit columns to every table:
    created_date, last_modified_date  (timestamptz, default now())
    created_by_id, last_modified_by_id (UUID FK -> users.id, ON DELETE SET NULL)

Hand-written (not autogenerated) so it contains ONLY the audit-column
additions — no unrelated index/constraint churn that autogenerate swept up
from pre-existing model/DB drift.

Revision ID: c1a2b3d4e5f6
Revises: b8j2f4g5h6i
Create Date: 2026-07-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1a2b3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "b8j2f4g5h6i"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every mapped table gets the audit columns. Kept as an explicit list so the
# migration is deterministic and reviewable.
TABLES: tuple[str, ...] = (
    "agent_audit_events",
    "agent_config_epochs",
    "agent_eval_runs",
    "agent_performance_daily",
    "agent_profiles",
    "agent_prompt_configs",
    "agent_runtime_logs",
    "agent_tool_invocations",
    "categories",
    "category_documents",
    "closing_briefings",
    "document_chunks",
    "entities",
    "entity_mentions",
    "entity_merge_suggestions",
    "graph_extraction_runs",
    "importance_runs",
    "kanban_boards",
    "kanban_columns",
    "meeting_chunks",
    "meetings",
    "org_memory_facts",
    "organizations",
    "participants",
    "prompt_deployments",
    "prompt_test_runs",
    "prompt_versions",
    "rag_chunk_access_events",
    "rag_citation_click_events",
    "rag_conversations",
    "rag_query_runs",
    "relationship_mentions",
    "relationships",
    "task_activity",
    "task_comments",
    "tasks",
    "team_documents",
    "teams",
    "template_behavior_profiles",
    "template_bundle_items",
    "template_bundles",
    "template_provisioning_jobs",
    "template_publish_events",
    "users",
    "workspace_behavior_overrides",
    "workspace_template_links",
)


def upgrade() -> None:
    for table in TABLES:
        op.add_column(
            table,
            sa.Column(
                "created_date",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        op.add_column(
            table,
            sa.Column(
                "last_modified_date",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        op.add_column(
            table,
            sa.Column("created_by_id", sa.UUID(), nullable=True),
        )
        op.add_column(
            table,
            sa.Column("last_modified_by_id", sa.UUID(), nullable=True),
        )
        op.create_foreign_key(
            f"fk_{table}_created_by",
            table,
            "users",
            ["created_by_id"],
            ["id"],
            ondelete="SET NULL",
        )
        op.create_foreign_key(
            f"fk_{table}_last_modified_by",
            table,
            "users",
            ["last_modified_by_id"],
            ["id"],
            ondelete="SET NULL",
        )


def downgrade() -> None:
    for table in TABLES:
        op.drop_constraint(f"fk_{table}_last_modified_by", table, type_="foreignkey")
        op.drop_constraint(f"fk_{table}_created_by", table, type_="foreignkey")
        op.drop_column(table, "last_modified_by_id")
        op.drop_column(table, "created_by_id")
        op.drop_column(table, "last_modified_date")
        op.drop_column(table, "created_date")
