"""Phase 8D: upgrade proposals + publish events.

Two new tables:

  1. **`template_upgrade_proposals`** — one per (workspace link,
     version-transition). Generated by `template_upgrade_detector`
     when a new template version is published. Admin reviews +
     accepts/rejects via the HTTP layer; on acceptance, a new
     `prompt_versions` row is created in the workspace through
     Phase 7B's publish_version. Append-only-ish: rows transition
     resolution_state but body fields don't mutate.

  2. **`template_publish_events`** — append-only audit when a global
     template version is published. The Celery detector scans this
     table for events whose proposals haven't been generated yet,
     and for nightly safety-net detection. BIGSERIAL PK.

Both tables are platform-owned in shape but org-scoped at use time:
proposals carry `organization_id`; publish_events are global.

`workspace_template_link_id` carries no FK per the Phase 6B audit-
survives-cascade convention: a proposal row outlives its link's
deletion, so admins can audit historical upgrade decisions even
after cleanup.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "o6c3d4e5f6a7"
down_revision = "n5b2c3d4e5f6"
branch_labels = None
depends_on = None


_PROPOSAL_STATE_CHECK = (
    "resolution_state IN ("
    "'open','accepted','partial_accepted','rejected','superseded'"
    ")"
)
_PROPOSAL_KIND_CHECK = (
    "entity_type IN ('category','agent_profile')"
)

_PUBLISH_KIND_CHECK = (
    "template_kind IN ('bundle','team','category','agent')"
)


def upgrade() -> None:
    # ----- template_publish_events -----
    op.create_table(
        "template_publish_events",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("template_kind", sa.String(length=16), nullable=False),
        sa.Column("template_slug", sa.String(length=64), nullable=False),
        sa.Column("from_version", sa.String(length=32), nullable=True),
        sa.Column("to_version", sa.String(length=32), nullable=False),
        sa.Column(
            "published_by", postgresql.UUID(as_uuid=True), nullable=True,
        ),
        sa.Column(
            "manifest_hash_before", sa.String(length=64), nullable=True,
        ),
        sa.Column(
            "manifest_hash_after", sa.String(length=64), nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
    )
    op.create_check_constraint(
        "ck_template_publish_events_kind",
        "template_publish_events", _PUBLISH_KIND_CHECK,
    )
    op.create_index(
        "ix_template_publish_events_kind_slug_created",
        "template_publish_events",
        ["template_kind", "template_slug", sa.text("created_at DESC")],
    )

    # ----- template_upgrade_proposals -----
    op.create_table(
        "template_upgrade_proposals",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "organization_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # No FK on workspace_template_link_id — audit outlives
        # cascades. Same rationale as Phase 6B access events.
        sa.Column(
            "workspace_template_link_id", sa.BigInteger(), nullable=False,
        ),
        # Denormalized so the inbox query can filter without a join.
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("source_template_kind", sa.String(length=16), nullable=False),
        sa.Column("source_template_slug", sa.String(length=64), nullable=False),
        sa.Column(
            "from_template_version", sa.String(length=32), nullable=False,
        ),
        sa.Column(
            "to_template_version", sa.String(length=32), nullable=False,
        ),
        # Full 3-way diff. Shape documented in upgrade.py:
        # {workspace_modular, template_old_modular, template_new_modular,
        #  workspace_retrieval, template_old_retrieval, template_new_retrieval,
        #  ...}
        sa.Column(
            "diff_json", postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'{}'::jsonb"),
        ),
        # Per-change toggles for the UI:
        # [{"key": "section:system", "kind": "modular", "status": "fast_forward"}, ...]
        sa.Column(
            "selectable_changes_json", postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
        # Sections/keys where workspace + template both changed
        # since the link was provisioned — UI flags these prominently.
        sa.Column(
            "conflict_keys_json", postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "resolution_state", sa.String(length=24),
            nullable=False, server_default="open",
        ),
        sa.Column(
            "accepted_changes_json", postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "decided_by_user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        # SET NULL on prompt_version deletion — the version may be
        # archived or recreated; audit history survives.
        sa.Column(
            "applied_prompt_version_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("prompt_versions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            nullable=False, server_default=sa.func.now(),
        ),
    )
    op.create_check_constraint(
        "ck_template_upgrade_proposals_state",
        "template_upgrade_proposals", _PROPOSAL_STATE_CHECK,
    )
    op.create_check_constraint(
        "ck_template_upgrade_proposals_entity_type",
        "template_upgrade_proposals", _PROPOSAL_KIND_CHECK,
    )
    # One proposal per (link, version-transition).
    op.create_unique_constraint(
        "uq_template_upgrade_proposals_link_versions",
        "template_upgrade_proposals",
        [
            "workspace_template_link_id",
            "from_template_version",
            "to_template_version",
        ],
    )
    op.create_index(
        "ix_template_upgrade_proposals_org_state_created",
        "template_upgrade_proposals",
        ["organization_id", "resolution_state", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_template_upgrade_proposals_link",
        "template_upgrade_proposals", ["workspace_template_link_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_template_upgrade_proposals_link",
        table_name="template_upgrade_proposals",
    )
    op.drop_index(
        "ix_template_upgrade_proposals_org_state_created",
        table_name="template_upgrade_proposals",
    )
    op.drop_constraint(
        "uq_template_upgrade_proposals_link_versions",
        "template_upgrade_proposals", type_="unique",
    )
    op.drop_constraint(
        "ck_template_upgrade_proposals_entity_type",
        "template_upgrade_proposals", type_="check",
    )
    op.drop_constraint(
        "ck_template_upgrade_proposals_state",
        "template_upgrade_proposals", type_="check",
    )
    op.drop_table("template_upgrade_proposals")

    op.drop_index(
        "ix_template_publish_events_kind_slug_created",
        table_name="template_publish_events",
    )
    op.drop_constraint(
        "ck_template_publish_events_kind",
        "template_publish_events", type_="check",
    )
    op.drop_table("template_publish_events")
